### ISSUE TITLE
Customization Suggestion <:

### ISSUE THREAD

**Issue by TheProgramerBone** [kwpugh/gobber_mod_forge#1]
More than a bug, it's a suggestion, as a clarification, I'm new in Github and I didn't understand very well if the suggestions are made here.
Anyway, mainly my suggestion lies in the configuration file of the mod, I would like it to allow to configure the effect of all the armor separately, without disabling the other perks, if you do not understand me, I mean edit for example:

Dragon armor: allow flying, but don't allow all effects to be healed.
Gobber armor: allow the effects of the armor, except the effect of negating the poison that occurs when the full set is equipped.
etc...

My suggestion lies mainly in more customization, gossiping a bit the jar code, it is not soooooo complicated to make my suggestion (or so I think). thank you very much, I am fascinated by the mod, I had been waiting for version 1.20.1 for a long time.

**Comment by kwpugh** [comment]
This is now standard in 1.21+, except for the flight, which will no longer have a config option to disable.

All armor perks are full-suit based, instead of by armor piece.  The perks for each armor set can be enabled/disabled separately.

**Comment by TheProgramerBone** [comment]
¡Amazing! ¡Thanks for reading my suggestion!
