### ISSUE TITLE
[1.21 NeoForge] Fortune Enchantment does not work properly.

### ISSUE THREAD

**Issue by OriginBo** [kwpugh/Gobber_mod_forge#10]
Issue：
When mining ores with an unenchanted pickaxe, drops are normal. However, when using a pickaxe with Fortune III enchantment, drops are not normal, behaving as if the ores are being collected with Silk Touch.

Version：
Minecraft 1.21
NeoForge 21.0.61-beta
Gobber NeoForge-1.21-2.10.5

GIF：
![gobber_bug6](https://github.com/kwpugh/gobber_mod_forge/assets/56879486/e86e5576-4aaa-4f98-adf1-3aad09cb2d1d)

**Comment by kwpugh** [comment]
The loot table for ore blocks changed in 1.21.
Fixed in next update.
