### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by SikiciBebek** [kwpugh/Gobber_mod_forge#11]
Its allways another Entity, i sadly dont know why :C. But it seems to be Gobber, which causes that.
[crash-2024-07-07_22.44.28-server.txt](https://github.com/user-attachments/files/16120727/crash-2024-07-07_22.44.28-server.txt)

**Comment by kwpugh** [comment]
That version of Gobber requires NeoForge 21.0.74 or higher due to a breaking change made by the Neo folks.

**Comment by SikiciBebek** [comment]
Ty! :D
