### ISSUE TITLE
All tiers of Gobber Foo have the same burn time in 1.21

### ISSUE THREAD

**Issue by Shadowglitchjpg** [kwpugh/Gobber_mod_forge#12]
Mod version: 2.10.3 for NeoForge
When I hover my mouse over Gobber Foo, Nether Gobber Foo or End Gobber Foo, it says "Burntime: 128000" for all of them. When I view the uses of any of them in JEI, it says that they all smelt 640 items each.

**Comment by kwpugh** [comment]
Ok.  I will push out an update.  You might want to either delete your config to get the changes or at least delete the foo section so it can re-generate.

**Comment by kwpugh** [comment]
Update pushed to curse forge.
