### ISSUE TITLE
Dragon Armor smithing recipes broken?

### ISSUE THREAD

**Issue by KWatDev** [kwpugh/Gobber_mod_forge#17]
I am making a modpack with over 300 mods with Dragon Armor as the main endgame armor of the pack, but for some reason all the End to Dragon Armor smithing recipes replace the End armor with Dragon Armor, making Dragon Armor uncraftable. I was editing the recipes with KubeJS a few weeks ago and the recipes were normal, but I came back to the pack today and they were broken. I even tried tweaking the recipes with a custom mod but it did nothing. It seems to be an issue with your mod, can you please fix it? Awesome mod though.

**Comment by kwpugh** [comment]
what version are you using?

**Comment by kwpugh** [comment]
These recipes?

![Screenshot 2024-08-15 at 4 47 49 PM](https://github.com/user-attachments/assets/2171e4d1-80a9-4160-9670-4fda422c7329)
![Screenshot 2024-08-15 at 4 48 03 PM](https://github.com/user-attachments/assets/36648a56-ef74-4cf2-91ea-4ba0b2fb71e5)

**Comment by kwpugh** [comment]
I tried in 1.20.1 and 1.21.1 and both worked fine.

**Comment by KWatDev** [comment]
Ok, I just tested it and it works, it seems to be a visual issue with JEI.
![2024-08-16_08 09 20](https://github.com/user-attachments/assets/dd45db4b-d33f-4318-b204-8b681b3025ee)
![2024-08-16_08 10 04](https://github.com/user-attachments/assets/e8246614-2905-483a-92bf-01dc1b9c991a)
