### ISSUE TITLE
Gobber Dropping TPS Server With Void Miner [Environmental Tech] 1.16.5

### ISSUE THREAD

**Issue by Minuando** [kwpugh/gobber_mod_forge#3]
I have the Gobber2 mod on my minecraft server, For some reason that I don't know, whenever the void miner CCU of the Environmental Tech mod is active with Gobber2 in the modpack, the TPS starts to drop for 30 to 180 seconds, after that the Console reports the following message.

[git.txt](https://github.com/kwpugh/gobber_forge/files/10583359/git.txt)

I want to know if it's a compatibility problem between Gobber and Void or some kind of limitation to not generate the ore by void miner ccu.

**Comment by kwpugh** [comment]
I don't know what if anything to do with this.
