### ISSUE TITLE
Configurable ore veins?

### ISSUE THREAD

**Issue by idenher1o** [kwpugh/Gobber_mod_forge#7]
Idk how to add tags i apologise.

Is there a way to configure ore veins? If not, what's the chance of that configuration being added?

**Comment by kwpugh** [comment]
Ore spawn is all controlled via data pack.

**Comment by idenher1o** [comment]
How do i access the data pack and configure it?

**Comment by kwpugh** [comment]
there are youtube vids on making data packs.

all of the world gen JSON files are in the mod's jar file under data folder, specifically worldgen.  

data packs are not particularly difficult to make, especially once you do the first one.

**Comment by kwpugh** [comment]
Also, ore gen can't be in the config file because the JSON files are generated in the dev environment before the mod is even published.
